name: Runner
version: ${project.version}
main: me.radoje17.runner.Runner
depend: [WorldEdit]
commands:
  runner:
    description: Komande za runner
  join:
    description: Magicna komanda
  leave:
    description: Izadji iz igre